version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./front
    ports:
      - "8085:8085"
    depends_on:
      - backend