version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8085:8085"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
